apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these labels are replica set labels
  labels:
    purpose: dp-demo
    project: roboshop
spec:
  replicas: 4
  selector:
  # these labels are used to select pods
    matchLabels:
      purpose: dp-demo
      project: roboshop 
  # pod defination
  template:
    metadata:
      labels:
        purpose: dp-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:trixie-perl